### PR TITLE
Update crc module

### LINKED ISSUE #5: CRC has changed a lot
Hi,

in the recent weeks CRC has apparently changed a lot as you can see here: https://pypi.org/project/crc/#history

At least on my Windows-PC I cannot make it work with CRC 4.1 as a lot of the namespaces and function calls have changed.

For now, the solution is to go back to an older version of CRC.

Best,
Florian

### PR DESCRIPTION
**Pull request by svenwanzenried**
I updated the crc module and applied the changed namespace.
However, I had not the chance to test it properly as I have no device at hand at the moment.
Please give it a try before merging

**Commit Message:**
Updated crc module requirement to >=4.1.0
Fixed namespace issues with updated crc module
Fixed #5

### CODE REVIEW

**Comment by kaanaksit** [comment]
In this new configuration, brightness values above 100 cause device errors:

```bash
Traceback (most recent call last):
  File "/home/kaan/repos/FisbaReadyBeam/test/test_on_off.py", line 19, in <module>
    sys.exit(test())
  File "/home/kaan/repos/FisbaReadyBeam/test/test_on_off.py", line 8, in test
    laser.set_brightness([200., 0., 0.])
  File "/home/kaan/repos/FisbaReadyBeam/FisbaReadyBeam/__init__.py", line 213, in set_brightness
    self.send_command(command)
  File "/home/kaan/repos/FisbaReadyBeam/FisbaReadyBeam/__init__.py", line 151, in send_command
    raise Exception(error)
Exception: Error signaled by device: 7, Value is out of range
```

**Comment by kaanaksit** [comment]
@svenwanzenried 
> I updated the crc module and applied the changed namespace. However, I had not the chance to test it properly as I have no device at hand at the moment. Please give it a try before merging
> 
> **Commit Message:** Updated crc module requirement to >=4.1.0 Fixed namespace issues with updated crc module Fixed #5

In this new configuration, brightness values above 100 cause device errors:

```bash
Traceback (most recent call last):
  File "/home/kaan/repos/FisbaReadyBeam/test/test_on_off.py", line 19, in <module>
    sys.exit(test())
  File "/home/kaan/repos/FisbaReadyBeam/test/test_on_off.py", line 8, in test
    laser.set_brightness([200., 0., 0.])
  File "/home/kaan/repos/FisbaReadyBeam/FisbaReadyBeam/__init__.py", line 213, in set_brightness
    self.send_command(command)
  File "/home/kaan/repos/FisbaReadyBeam/FisbaReadyBeam/__init__.py", line 151, in send_command
    raise Exception(error)
Exception: Error signaled by device: 7, Value is out of range
```

I thought it might be scaling the input to 0-100 rather than 0-255. But I checked it physically, it is dimmer in this 0-100 range, suggesting that we should be able to input larger values. Please correct me if I am wrong.

**Comment by svenwanzenried** [comment]
> @svenwanzenried 
> > I updated the crc module and applied the changed namespace. However, I had not the chance to test it properly as I have no device at hand at the moment. Please give it a try before merging
> > 
> > **Commit Message:** Updated crc module requirement to >=4.1.0 Fixed namespace issues with updated crc module Fixed #5
> 
> In this new configuration, brightness values above 100 cause device errors:
> 
> ```python
> Traceback (most recent call last):
>   File "/home/kaan/repos/FisbaReadyBeam/test/test_on_off.py", line 19, in <module>
>     sys.exit(test())
>   File "/home/kaan/repos/FisbaReadyBeam/test/test_on_off.py", line 8, in test
>     laser.set_brightness([200., 0., 0.])
>   File "/home/kaan/repos/FisbaReadyBeam/FisbaReadyBeam/__init__.py", line 213, in set_brightness
>     self.send_command(command)
>   File "/home/kaan/repos/FisbaReadyBeam/FisbaReadyBeam/__init__.py", line 151, in send_command
>     raise Exception(error)
> Exception: Error signaled by device: 7, Value is out of range
> ```
> 
> I thought it might be scaling the input to 0-100 rather than 0-255. But I checked it physically, it is dimmer in this 0-100 range, suggesting that we should be able to input larger values. Please correct me if I am wrong.

I'm sorry, I believe I don't understand your issue correctly.
The function set_brightness() is supposed to accept the brightness values in percent of full scale brighness.
Also the communication protocol to the device accepts only values in percent. Therefore, every value above 100.5% will result in an exception.
Did you say, you set your value to 100% and there is still lesser power beeing emitted than it used to be?

**Comment by kaanaksit** [comment]
Ok, you suggest that in this range of values from zero to hundred. We use a percentage scale. Because previously,  I used brightness values between 0-255 (the previous version before this pull request). Please ignore my last message.

**Comment by svenwanzenried** [comment]
I did not change anything in the composition of the datapackets. So I assume you somehow used a modified version of the library. As you can see in the code (and even in the docstring) there were percentage befor this pull request.
But anyway, it would surely be possible to create a function to allow for values in the full 8-bit range which then get converted down to percentage values for transmission, if that would fit your needs better...
Let me know if you think the addition would be worth the effort 👌

**Pull request merged**
